apiVersion: v1
kind: ServiceAccount
metadata:
  name: thousandeyes-sync-sa
  namespace: ops  # Change this to your namespace

---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: thousandeyes-sync-role
  namespace: ops
rules:
- apiGroups: [""]
  resources: ["configmaps"]
  verbs: ["get", "list", "watch"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: thousandeyes-sync-binding
  namespace: ops
subjects:
- kind: ServiceAccount
  name: thousandeyes-sync-sa
  namespace: ops
roleRef:
  kind: Role
  name: thousandeyes-sync-role
  apiGroup: rbac.authorization.k8s.io
