# 
# echo -n "your-thousandeyes-api-token" | base64

apiVersion: v1
kind: Secret
metadata:
  name: thousandeyes-secret
  namespace: ops  # Change if needed
type: Opaque
data:
  apiToken: {{ "your-thousandeyes-api-token" | b64enc }}



