apiVersion: apps/v1
kind: Deployment
metadata:
  name: thousandeyes-sync
  namespace: ops
  labels:
    app: thousandeyes-sync
spec:
  replicas: 1
  selector:
    matchLabels:
      app: thousandeyes-sync
  template:
    metadata:
      labels:
        app: thousandeyes-sync
    spec:
      serviceAccountName: thousandeyes-sync-sa
      containers:
      - name: thousandeyes-sync
        image: gorositopablo/thousandeyes-sync:latest
        ports:
          - name: http-metrics
            containerPort: 8000
            protocol: TCP
          - name: http-health
            containerPort: 5000
            protocol: TCP
        env:
        - name: TE_API_TOKEN
          valueFrom:
            secretKeyRef:
              name: thousandeyes-secret
              key: apiToken
        - name: NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        livenessProbe:
          httpGet:
            path: /health
            port: 5000
          initialDelaySeconds: 5
          periodSeconds: 10

